site_name: Commonground Skeleton App
repo_url: https://github.com/ConductionNL/nl-design-skeleton-gatsby
edit_uri: docs/
    Home.md
    Contributing.md
    Getting Started.md
    Design Decisions.md
    Features.md
    Security.md
theme: readthedocs
